<?php

const MELONLY_AUTHOR = 'Dominik Rajkowski | GitHub: Doc077';
const MELONLY_PHP_MIN_VERSION = 8.1;
const MELONLY_PHP_MIN_VERSION_ID = 80100;
const MELONLY_VERSION = '7.25.0';
const MELONLY_VERSION_RELEASE_DATE = 'May 2022';
const MELONLY_VERSION_STAGE = 'STABLE';
